name: test
on:
  workflow_dispatch:

jobs:
  suite:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Sanity
        run: |
          node --version
          git --version
      - name: Install dependencies
        run: npm install
      - name: Run test suite
        run: npm test